steps:
  - label: "Examine container environment."
    commands:
      - ls
      - find . -name "build-wheel-experimental2.sh"
      - whoami
    plugins:
      - docker#v3.7.0:
          image: "quay.io/pypa/manylinux2014_x86_64"
