# Job to run a Ray program in its own pod. Assumes that a Ray cluster is already
# running.
apiVersion: batch/v1
kind: Job
metadata:
  generateName: ray-test-job-
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: ray
          image: rayproject/ray:nightly
          imagePullPolicy: Always
          command: [ "/bin/bash", "-c", "--" ]
          args:
            - "wget https://raw.githubusercontent.com/DmitriGekhtman/ray/move-k8s-test-scripts/doc/kubernetes/example_scripts/job_example.py &&
              python job_example.py"
          env:
            - name: EXAMPLE_PROGRAM_PATH
              value: "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/kubernetes/example_scripts/job_example.py"
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
